baseURL = "https://bd.frege2godel.me/"
# baseURL = "http://localhost:1313/"
title = "Holy Frege"
email = "hoyoul.park@gmail.com"
footer = "Built with Org-mode and Hugo."

pygmentsStyle = "onedark"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

languageCode = "ko"
hasCJKLanguage = true

[markup]
  [markup.highlight]
    lineNoStart = 1
    # lineNos = true
    # tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
    # [markup.goldmark.renderer.highlight]
    #   codeFences = true
    #   guessSyntax = true
    #   lineNumbers = true
    #   style = "monokai" # 적용할 스타일을 선택
  # [markup.highlight]
    # codeFences = true
    # guessSyntax = false
    # hl_Lines = ""
    # lineNoStart = 1
    # lineNos = false
    # lineNumbersInTable = true
    # noClasses = true
    # style = "friendly"
    # tabWidth = 4
