:PROPERTIES:
:ID:       2B6F50CF-2AC2-4E7C-A2ED-5CBAA1416816
:mtime:    20231029160604
:ctime:    20231029160604
:END:
#+title: [english] where are you-annie2 
#+AUTHOR: hoyoul
#+EMAIL: hoyoul@whitebrew.com
#+DATE: <2023-10-29 Sun>
#+DESCRIPTION: where are you
#+HUGO_DRAFT: true
* Hey, Where are you
* Dear annie
I'm wondering whether you could settle a dispute between my friend
"Laura" and me. She thinks it's rude to "ghost"-leave parties without
saying bye. I think it's fine.

For example, last weekend, our mutual friend had a barbecue. This
particular friend is a social butterfly, so there were probably close
to 75 people there. I knew a dozen or so of the guests. I enjoyed
catching up with them and meeting some new people, but after a couple
of hours, my socializing meter was about up and I was ready to go home
and get to bed.

I didn't want to take the trouble to say bye to everyone I knew there,
so I just said good night to the people in my immediate vicinity and
then stepped out quietly. About an hour later, Laura texted asking
where I'd gone. When I told her I was already at home, she got angry
and said it was rude for me not to say goodbye.

I really have never thought of it as rude. I think of it as a
timesaver for everyone. I hate awkwardly interrupting the flow of
conversations to tell people I'm leaving, especially because then
other people usually chime in, "Oh, I should get going too," and I
feel as if I've killed the party. I just want to slip out quietly and
let everyone else keep doing their thing.

what do you think, Annie? Is it bad manners to ghost?

- Tiptoeing Toward the Exit
