:PROPERTIES:
:ID:       CC616D39-BD27-4DFE-A0FD-1649026C22CD
:mtime:    20230903084113
:ctime:    20230903084113
:END:
#+title: [idea] how to come out idea.
#+AUTHOR: holy
#+EMAIL: hoyoul.park@gmail.com
#+DATE: <2023-09-03 Sun>
#+DESCRIPTION: idea 만드는 법
#+HUGO_DRAFT: true
* red ocean
red ocean은 경쟁업체가 많아서 들어가기 힘든 업종이란 뜻, 역으로 말하면
수요가 많다는 것이다. 여기선 그 업종을 해선 안되고, 그 업종에서 필요한
원자재를 생각해야 한다. 아니면 그 업종과 관련있는 업종을 선택하는
것이다. 예를 들어 하루 1000개 팔리는 짜장면집이 있다면, 짜장면 만드는
기계나 짜장면에 사용되는 신선한 야채를 팔아야 한다. 아니면, 짜장면이
잘팔리면 담배가 땡기기 때문에 담배집을 해도 된다.
* context
이건 아이디어를 생각하는 또 다른 방법인데, 어떤 물체건 간에,
context(다른 obejct와의 relation에 따라 의미가 달라진다:
ex)environment[시간 장소,사람이나 다른 object])에 따라 object가 가진
성질이나 동작이 일상과는 다르게 된다. 칼이 다른 object인
의사,요리사,도둑에게 가면 그 성질이 변한다. 내 특허의 아이디어도 내가
watch를 가지고 짐을 가지고 차 뒤로 가면 트렁크가 열린다. 3개의
object가 관여되었다. context는 여러개의 object가 관여 될수 있다. 만일
내가 어떤 앱을 만든다면, 밤이 되면 dark모드로 하고 형광색으로 요소를
보여준다면, 이것은 내앱과 시간이라는 요소의 관계에서 만들어진
아이디어다. 만일 시끄러운 장소에서 내 앱이 어떤 정보를 받는다면 이것은
vibrator로 표현해야 한다. 말을 할수 없는 상황에서 터치로 119를
보낼수도 있다.
* 예측되는 behavior를 자동화 (context-triggered actions)
지금 생각하는 것은 사람을 기준으로 한다. 사람이 어떤 장소에 가거나,
어떤 시간이 될때, 아니면 어떤 다른 사람과 만나거나, 어떤 물체에
접한다면 행동을 예측할 수 있다. 예를 들어서 냉장고에 사람이 가면
display로 현재 음식 정보를 보여준다거나, 밤에 화장실을 가면 자동으로
불이 켜지는것은 예측되는 behavior를 자동화한 것이다. 밤에 강남에 가면
자동으로 키커지는 신발도 그 예다.  if then문으로 생각해도 된다. 어떤
예측가능한 행동은 그 사람만의 독단적인 행동일 수도 있고 통계값을
이용해서도 예측할 수 있다. 만일 어떤 사람이 자동차 가스가 없는
상태에서 주유소를 검색했다면, 이 사람은 주유소를 찾는다는 것을 알 수 있다.

* context-awareness
이런것을 학문적 용어로 context-awareness라고 한다.

* context와 behavior, 그리고 intelligence
어떤 context는 behavior를 하게 만든다. 예를 들어서 가스 냄새가 나는
지하실에서 가스가 있는 지 확인하기 위해서 라이터를 킬 수도
있다. 이러면 inteligence는 없지만, context가 어떤 behavior를 만들어
낸다.
