:PROPERTIES:
:ID:       07503E61-EDF7-4352-ACDE-5CC20E65B9A5
:mtime:    20230608140158 20230608122858 20230607223025 20230607172238
:ctime:    20230607172238
:END:
#+title: python_summary1
#+AUTHOR: holy
#+EMAIL: hoyoul.park@gmail.com
#+DATE: <2023-06-07 Wed>
#+DESCRIPTION: emacs에서 python의 설정과 python의 개념. 
#+HUGO_DRAFT: true
* python이란?
python은 함수형언어가 아니라, =객체 지향 언어= 다. python은 모든 것을
객체로 바라본다. 따라서 우리도, python 코드의 모든것을 객체로
생각하고, 객체로 해석해야 한다.
* python의 개발 환경
python을 사용하려면 setting이 필요하다. computer에 전원을 넣고 바로
python 코드를 작성하고 실행하는 그림을 상상하지 말자. 코딩하는 방법은
여러가지다. 코딩할 수 있는 다양한 editor가 존재하고, 그 많은
editor에서 선택을 해야한다. 나는 emacs를 선택했다. emacs를 선택해서
끝나는게 아니다. 다양한 방법이 존재한다. elpy를 사용해서 코딩할수도
있고, lsp로 코딩할수도 있고, jupyter notebook으로 코딩할수도 있고,
google colab과 연결해서 사용할 수도 있다. 짜증나지만, 많은 방법이
있다. 여튼 중요한건 난 emacs를 사용한다는 것이고 emacs를
사용한다는 것은, =everything is possbile= 이다. 한계는 없다.

** emacs 설정
python code를 작성하는 editor로 emacs를 사용한다. emacs에서 python을
작성하기위한 setting이 필요하다. lsp를 사용해서 속시원하게 사용하는게
추천되지만, 나는 2014년 맥북 사용자다. 분수에 맞게 코딩을 하자.
jupyter notebook이나 google colab을 사용해서 ipython
interpreter(kernel)을 이용하려면 다음 [[file:emacs_jupyter_noteboo_settings.org][설정을]] 참고하자. anaconda로
작성하려면 [[file:emacs_anaconda_settings.org][여기(from here)]]를 참조한다. 그래도 지금 대세인 lsp를
사용하겠다고 한다면 [[file:emacs_python_lsp_setting.org][여기(from here)]]을 참조해라.



